sudo: false
language: node_js
node_js:
    - "6"
    - "8"
    - "10"
    - "12"
script: npm run travis
after_success: npm run coverage
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
